port = 4023 # todo: 删除
db_path = "./predict.db"
dump_path = "./dump"  #
predict_worker_num = 5  #  启动分析的子进程数量
notify_svr_url = "http://127.0.0.1:4023/"  # todo: 删除
notify_timeout = 5  # 通知的超时时间，单位：秒
redis_stream_tag = "xinlan_predict_0001_stream"  # todo: 删除
static_dir = "../dron-web-server/static"
svr_root_url = "http://localhost/static"  # 用于返回图片的url地址
frame_interval_count = 120 # 相隔多少帧处理生成的一张图片
watch_interval = 30 # 每隔多少秒检测一次
rtmp_max_timeout = 1800 # rtmp流dump最长的持续时间
main_cmd = "rtmp-frame" # 工程运行的命令
max_duraion = 1200 # 最长运行时间
is_test = true
